MvcTiendaPrueba/Controllers/CestaController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTiendaPrueba.Extensions;
using MvcTiendaPrueba.Models;
using MvcTiendaPrueba.Repositories;

namespace MvcTiendaPrueba.Controllers
{
    public class CestaController : Controller
    {
        private RepositoryTienda repo;
        public CestaController(RepositoryTienda repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {

            return View();
        }



    }
}

MvcTiendaPrueba/Controllers/TiendaController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTiendaPrueba.Data;
using MvcTiendaPrueba.Extensions;
using MvcTiendaPrueba.Models;
using MvcTiendaPrueba.Repositories;

namespace MvcTiendaPrueba.Controllers
{
    public class TiendaController : Controller
    {
        private RepositoryTienda repo;
        private TiendaContext context;

        public TiendaController(RepositoryTienda repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            var categorias = await repo.GetCategoriasAsync();
            ViewData["CATEGORIAS"] = categorias;
            var comentarios = repo.GetComentarios();
            ViewData["COMENTARIOS"] = comentarios;
            return View();
        }


        /*******************************/

        public async Task<IActionResult> DetailsProducto
            (int idproducto)
        {
            List<Comentario> comentarios = await this.repo.FindComentariosAsync(idproducto);
            HttpContext.Session.SetObject("COMENTARIOS", comentarios);

            Producto producto = await this.repo.FindProductosAsync(idproducto);
            return View(producto);
        }

        public async Task<IActionResult> PaginarGrupoProductos(int? posicion)
        {
            var categorias = await repo.GetCategoriasAsync();
            ViewData["CATEGORIAS"] = categorias;
            if (posicion == null)
            {
                posicion = 1;
            }
            int registros = await this.repo.GetNumeroProductosAsync();
            List<Producto> productos = await this.repo.GetGrupoProductosAsync(posicion.Value);
            ViewData["REGISTROS"] = registros;
            ViewData["NumeroPaginaActual"] = posicion; // Pasa el número de página actual a la vista
            return View(productos);
        }

        public async Task<IActionResult> ProductosCategoria(int? posicion, int idcategoria)
        {
            var categorias = await repo.GetCategoriasAsync();
            ViewData["CATEGORIAS"] = categorias;
            if (posicion == null)
            {
                posicion = 1;
            }
           
                List<Producto> productos = await this.repo.GetGrupoProductosCategoriaAsync(posicion.Value,idcategoria);
                int registros = await this.repo.GetNumeroProductosCategoriaAsync(idcategoria);
                ViewData["REGISTROS"] = registros;
                ViewData["IDCATEGORIA"] = idcategoria;
                ViewData["NumeroPaginaActual"] = posicion; // Pasa el número de página actual a la vista
                return View(productos);
        }


        public async Task<IActionResult> Categorias()
        {
            List<Categoria> categorias = await this.repo.GetCategoriasAsync();
            return View(categorias);
        }

        /************************CESTA*****************************************/

        public async Task<IActionResult> Cesta()
        {
            List<int> cesta = HttpContext.Session.GetObject<List<int>>("CESTA");
            if (cesta != null)
            {
                List<Producto> productos = await this.repo.GetProductosSessionAsync(cesta);
                return View(productos);
            }
            return View();
        }

        public IActionResult AnyadirProductoCesta(int? idproducto)
        {
            if (idproducto != null)
            {
                List<int> cesta;
                if (HttpContext.Session.GetString("CESTA") == null)
                {
                    cesta = new List<int>();
                }
                else
                {
                    cesta = HttpContext.Session.GetObject<List<int>>("CESTA");
                }
                cesta.Add(idproducto.Value);
                HttpContext.Session.SetObject("CESTA", cesta);
            }
            return RedirectToAction("PaginarGrupoProductos");
        }

        public async Task<IActionResult> EliminarProductoCesta(int? idproducto)
        {
            if (idproducto != null)
            {
                List<int> cesta =
                    HttpContext.Session.GetObject<List<int>>("CESTA");
                cesta.Remove(idproducto.Value);
                if (cesta.Count() == 0)
                {
                    HttpContext.Session.Remove("CESTA");
                }
                else
                {
                    HttpContext.Session.SetObject("CESTA", cesta);
                }
            }
            return RedirectToAction("CESTA");
        }

        /**************************FAVORITOS***************************************/
        public async Task<IActionResult> Favoritos()
        {
            List<int> favoritos = HttpContext.Session.GetObject<List<int>>("FAVORITOS");
            if (favoritos != null)
            {
                List<Producto> productos = await this.repo.GetProductosSessionAsync(favoritos);
                return View(productos);
            }
            return View();
        }

        public IActionResult AnyadirProductoFavoritos(int? idproducto)
        {
            if (idproducto != null)
            {
                List<int> favoritos;
                if (HttpContext.Session.GetString("FAVORITOS") == null)
                {
                    favoritos = new List<int>();
                }
                else
                {
                    favoritos = HttpContext.Session.GetObject<List<int>>("FAVORITOS");
                }
                favoritos.Add(idproducto.Value);
                HttpContext.Session.SetObject("FAVORITOS", favoritos);
            }
            return RedirectToAction("PAginarGrupoProductos");
        }

        public async Task<IActionResult> EliminarProductoFavoritos(int? idproducto)
        {
            if (idproducto != null)
            {
                List<int> favoritos =
                    HttpContext.Session.GetObject<List<int>>("FAVORITOS");
                favoritos.Remove(idproducto.Value);
                if (favoritos.Count() == 0)
                {
                    HttpContext.Session.Remove("FAVORITOS");
                }
                else
                {
                    HttpContext.Session.SetObject("FAVORITOS", favoritos);
                }
            }
            return RedirectToAction("FAVORITOS");
        }

        /******************** PEDIDOS ****************************/
        private int ObtenerIdUsuario()
        {
            // Verificamos si el usuario está presente en la sesión
            Usuario usuario = HttpContext.Session.GetObject<Usuario>("USUARIO");

            // Si el usuario está presente en la sesión, devolvemos su ID
            // Si no está presente o es nulo, devolvemos algún valor predeterminado o manejamos la situación según sea necesario
            return usuario != null ? usuario.IdUsuario : 0;
        }
        public async Task<IActionResult> RealizarCompra()
        {
            // Obtenemos el ID del usuario desde la sesión
            int idUsuario = ObtenerIdUsuario();

            // Obtenemos la lista de productos en la cesta desde la sesión
            List<int> cesta = HttpContext.Session.GetObject<List<int>>("CESTA");

            // Obtenemos los detalles de los productos en la cesta desde la base de datos
            List<Producto> productosEnCesta = await this.repo.GetProductosEnCestaAsync(cesta);

            // Creamos el pedido
            Pedido pedido = await this.repo.CreatePedidoAsync(idUsuario, productosEnCesta);

            // Limpiamos la cesta después de crear el pedido
            HttpContext.Session.Remove("CESTA");

            // Redirigimos a alguna página de confirmación o cualquier otra acción que necesites
            return RedirectToAction("PaginarGrupoProductos");
        }

        public async Task<IActionResult> PedidosUsuario()
        {
            int idUsuario = ObtenerIdUsuario();
            List<DetallePedidoView> pedidosUsuarios = await this.repo.GetProductosPedidoUsuarioAsync(idUsuario);
            return View(pedidosUsuarios);
        }

    }
}

MvcTiendaPrueba/Views/Tienda/Cesta.cshtml
@model List<Producto>

<head>
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />

</head>

<a asp-controller="Tienda" asp-action="PaginarGrupoProductos" style="margin:auto">
    <span class="material-symbols-outlined" style="color: black; border: 1px solid black; border-radius: 20px;">
        arrow_back
    </span>
</a>

<body>


    @if (Model == null)
    {
        <h2 class="text-danger" style="text-align: center;">No hay productos en tu carrito</h2>
    }
    else
    {
        <div style="display: flex; align-items: center; justify-content: space-between;margin: 1px 20px 1px 20px;">
            <h3 class="text-primary mt-3">Productos en carrito: @Model.Count()</h3>
            <h3 class="text-success mt-2">Precio total: @Model.Sum(c => c.Precio)€</h3>
        </div>

        <div class="container mt-5">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
                @foreach (Producto pro in Model)
                {
                    <div class="col">
                        <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem;">
                            <div class="d-flex justify-content-between align-items-center card-body">
                                <img src="~/images/cenicero.png" style="width: 9%;margin-left: 30px;">
                                <div>
                                    <h4 class="card-title" style="font-weight: bold;">@pro.Nombre</h4>
                                    <p class="card-text">@pro.Descripcion</p>
                                </div>
                                <div class="ml-auto">
                                    <p style="font-weight: bold;">@pro.Precio €</p>
                                </div>
                                <div style="margin-right: 25px">
                                    <a asp-controller="Tienda" asp-action="EliminarProductoCesta"
                                       asp-route-idproducto="@pro.IdProducto" class="btn btn-danger">
                                        <span class="material-symbols-outlined">delete</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>



        <a asp-controller="Tienda" asp-action="RealizarCompra"
           class="btn btn-success w-100 mt-3">
            Realizar compra
        </a>
    }

</body>


@section scripts {
    <script>

    </script>
}

MvcTiendaPrueba/Views/Tienda/DetailsProducto.cshtml
@model Producto

@{
    List<int> cesta = Context.Session.GetObject<List<int>>("CESTA");
    List<int> favoritos = Context.Session.GetObject<List<int>>("FAVORITOS");
    List<Comentario> comentarios = Context.Session.GetObject<List<Comentario>>("COMENTARIOS");
    string? user = Context.Session.GetString("USUARIO");

}

<head>
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .checked {
            color: orange;
        }

        footer {
            margin-top: auto; /* Hace que el pie de página se pegue al final del contenedor */
        }
    </style>
</head>
<body style="margin-top: 60px;margin-bottom: 20px">
    <a asp-controller="Tienda" asp-action="ProductosCategoria" asp-route-idcategoria="@Model.IdCategoria" style="margin:auto">
        <span class="material-symbols-outlined" style="color: black; border: 1px solid black; border-radius: 20px;">
            arrow_back
        </span>
    </a>
    
    <ul class="services" >
        <li class="card-large card-dark card-wide" id="serv-groom">
            <div class="card-image"><img src="~/images/cenicero.png"></div>
            <ul>
                @Model.Nombre
                <span class="subtitle">@Model.Descripcion</span>
                <li><a href="#">Precio: </a><span>@Model.Precio</span></li>
                <div>
                    @if (user is null)
                    {
                        <a class="btn w-100" style="background-color: #9acb8d;" href="~/Account/Login">Iniciar sesión para añadir al carrito</a>
                        <a class="btn w-100" style="background-color: #9acb8d;" href="~/Account/Login">Iniciar sesión para añadir a favoritos</a>
                    }
                    else
                    {
                        @if (cesta != null)
                        {
                            @if (!cesta.Contains(@Model.IdProducto))
                            {
                                <a asp-controller="Tienda"
                                   asp-action="AnyadirProductoCesta"
                                   asp-route-idproducto="@Model.IdProducto"
                                   class="btn w-100" style="background-color: #9acb8d;">
                                    Añadir producto a carrito
                                </a>
                            }
                            else
                            {
                                <button class="btn btn-secondary w-100">
                                    Producto ya en la cesta
                                </button>
                            }
                        }
                        else
                        {
                            <a asp-controller="Tienda"
                               asp-action="AnyadirProductoCesta"
                               asp-route-idproducto="@Model.IdProducto"
                               class="btn w-100" style="background-color: #9acb8d;">
                                Añadir producto a carrito
                            </a>
                        }

                        @if (favoritos != null)
                        {
                            @if (!favoritos.Contains(@Model.IdProducto))
                            {
                                <a asp-controller="Tienda"
                                   asp-action="AnyadirProductoFavoritos"
                                   asp-route-idproducto="@Model.IdProducto"
                                   class="btn w-100" style="background-color: #9acb8d;">
                                    Añadir producto a favoritos
                                </a>
                            }
                            else
                            {
                                <button class="btn btn-secondary w-100">
                                    Producto ya en favoritos
                                </button>
                            }
                        }
                        else
                        {
                            <a asp-controller="Tienda"
                               asp-action="AnyadirProductoFavoritos"
                               asp-route-idproducto="@Model.IdProducto"
                               class="btn w-100" style="background-color: #9acb8d;">
                                Añadir producto a favoritos
                            </a>
                        }
                    }

                </div>
            </ul>
        </li>
    </ul>

    <div class="container mt-5" >
        @if (comentarios.Any())
        {
            <h2>Comentarios</h2>
        }
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-5">
            @foreach (Comentario com in comentarios)
            {
                <div class="col">
                    <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem">
                        <div class="card-body">
                            <h5 class="card-title">@com.IdComentario</h5>
                            <p class="card-text">@com.ComentarioTexto</p>
                            @for (int i = 0; i < 5; i++)
                            {
                                <span class="fa fa-star @(i < com.Valoracion ? "checked" : "")"></span>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>

MvcTiendaPrueba/Views/Tienda/Favoritos.cshtml
@model List<Producto>

<head>
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />

</head>

<a asp-controller="Tienda" asp-action="PaginarGrupoProductos" style="margin:auto">
    <span class="material-symbols-outlined" style="color: black; border: 1px solid black; border-radius: 20px;">
        arrow_back
    </span>
</a>

<body>


    @if (Model == null)
    {
        <h2 class="text-danger" style="text-align: center;">No hay favoritos</h2>
    }
    else
    {
        <div style="display: flex; align-items: center; justify-content: space-between;margin: 1px 20px 1px 20px;">
            <h3 class="text-primary mt-3">Productos en favoritos: @Model.Count()</h3>
        </div>

        <div class="container mt-5">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
                @foreach (Producto pro in Model)
                {
                    <div class="col">
                        <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem;">
                            <div class="d-flex justify-content-between align-items-center card-body">
                                <img src="~/images/cenicero.png" style="width: 9%;margin-left: 30px;">
                                <div>
                                    <h4 class="card-title" style="font-weight: bold;">@pro.Nombre</h4>
                                    <p class="card-text">@pro.Descripcion</p>
                                </div>
                                <div class="ml-auto">
                                    <p style="font-weight: bold;">@pro.Precio €</p>
                                </div>
                                <div style="margin-right: 25px">
                                    <a asp-controller="Tienda" asp-action="EliminarProductoFavoritos"
                                       asp-route-idproducto="@pro.IdProducto" class="btn btn-danger">
                                        <span class="material-symbols-outlined">delete</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }

</body>


@section scripts {
    <script>

    </script>
}

MvcTiendaPrueba/Views/Tienda/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
    Layout = null;
    var comentarios = ViewData["COMENTARIOS"] as List<Comentario>;
    var categorias = ViewData["CATEGORIAS"] as List<Categoria>;
    string? user = Context.Session.GetString("USUARIO");
    bool esAdmin = Context.Session.GetObject<bool>("EsAdmin");
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mi Tienda Artesanal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/css/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/css/slick-theme.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"  />
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />


    <style>

        html, body {
            height: 100%;
        }

        .main-container {
            min-height: calc(100% - 56px); /* Resta la altura de la barra de navegación */
            display: flex;
            flex-direction: column;
        }

        footer {
            margin-top: auto; /* Hace que el pie de página se pegue al final del contenedor */
        }

        .checked {
            color: orange;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <div>
                <a class="navbar-brand" asp-controller="Tienda" asp-action="Index">ResinCrafted</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarResponsive" style="justify-content:end; padding-top: 10px">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Tienda" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Tienda" asp-action="PaginarGrupoProductos">Productos</a>
                    </li>
                    @if (user is not null)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Tienda" asp-action="Cesta">Cesta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Tienda" asp-action="Favoritos">Favoritos</a>
                        </li>
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="material-symbols-outlined">
                                person
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            @if (user is not null)
                            {
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Tienda" asp-action="PedidosUsuario">Mis pedidos</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Login">Mi perfil</a>
                                </li>
                                @if (esAdmin)
                                {
                                    <li >
                                        <a class="dropdown-item text-dark" asp-controller="Account" asp-action="PanelAdmin">Panel Admin</a>
                                    </li>
                                }
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Logout">Log Out</a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Login">Log In</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="multiple-items" style="width: 90%; display: flex; margin: auto;">
        <div><img src="~/images/bolis.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/llavero.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/joyas.jpg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/bolis.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/llavero.jpeg" class="img-fluid rounded-start" alt="..."></div>
        <div><img src="~/images/joyas.jpg" class="img-fluid rounded-start" alt="..."></div>
    </div>

    <section>
        <h2>Categorías</h2>

        <ul class="shop-pets">
            @foreach (Categoria cat in categorias)
            {
                <li class="card-large card-light" id="sup-dog">
                    <ul style="margin-top:20px; text-align:center">
                        @cat.Nombre
                        <div class="card-image"><img src="~/images/cenicero.png" style="border-radius: 1px 50px 1px 50px"></div>
                        <a asp-controller="Tienda" asp-action="ProductosCategoria" asp-route-idcategoria="@cat.IdCategoria" style="margin:auto"><button class="btn-outline-light">Ver productos</button></a>
                    </ul>
                </li>
            }

        </ul>
    </section>


    <!--<footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Derechos de autor &copy; 2024 - Mi Tienda Artesanal</p>
        </div>
    </footer>-->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>


        <script>

            $('.multiple-items').slick({
                infinite: true,
                slidesToShow: 3,
                slidesToScroll: 3,
                autoplay: true,
                autoplaySpeed: 2000,
            });
        

        </script>
    
    
</body>
</html>

MvcTiendaPrueba/Views/Tienda/PedidosUsuario.cshtml
@model List<DetallePedidoView>

    <head>
    <link rel="stylesheet" href="~/css/misestilos.css" asp-append-version="true" />

</head>

<body>

    @if (Model == null || Model.Count == 0)
    {
        <h2 class="text-danger" style="text-align: center;">No hay pedidos realizados</h2>
    }
    else
    {
        <h1>Pedidos realizados</h1>

        <div class="container mt-5">
            @foreach (var pedido in Model.GroupBy(p => p.IdPedido))
            {
                <div class="row mb-4">
                    <div class="col" style="background-color: #9acb8d">
                        <h3>Pedido @pedido.Key</h3>
                    </div>
                </div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
                    @foreach (var detallePedido in pedido)
                    {
                        <div class="col">
                            <div class="card shadow-sm" style="border-radius: 35px; margin-bottom:1rem">
                                <div class="card-body">
                                    <h5 class="card-title">@detallePedido.NombreProducto</h5>
                                    <p class="card-text">@detallePedido.PrecioUnitario €</p>
                                    <p class="card-text" style="font-weight: bold">Total pedido: @detallePedido.TotalPedido €</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    }


</body>